# Generated by Django 4.2 on 2023-05-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('country', 'city', 'street', 'house_number')},
        ),
    ]
