# Generated by Django 4.2 on 2023-05-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0002_alter_address_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set(),
        ),
    ]
