# Generated by Django 4.2 on 2023-05-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0003_alter_address_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
